name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: |
        git submodule update --init --recursive
        dotnet restore CamlBuilder4000.sln
        msbuild "CamlBuilder4000.sln" /p:Configuration=Release /verbosity:minimal
        dotnet test /CamlBuilder.Tests/CamlBuilder.Tests.fsproj
